services:
  # Serviço do Banco de Dados
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${VITE_USER_DB}
      POSTGRES_PASSWORD: ${VITE_PASSWORD_DB}
      POSTGRES_DB: ${VITE_DATABASE_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${VITE_USER_DB} -d ${VITE_DATABASE_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Serviço do Servidor Express
  api:
    build: .
    container_name: express_server
    restart: always
    ports:
      - "${VITE_PORT}:${VITE_PORT}"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
